ptcrealitylab/vuforia-spatial-edge-server

libraries/webFrontend.js
package-lock.json
package.json

Ends up incorporating the eslint changes but I'll rebase after that's approved

Remove change case

---

libraries/hardwareInterfaces.js
libraries/objectDefaultFiles/logicNodeSettings.js
libraries/objectDefaultFiles/object.js

I adjusted all APIs to rename frame to tool and reality to spatial.
@benptc can you test these APIs with all tools and the hardware interfaces?
Everything should be backward compatible.

Changed all API calls that contain the word frame to tool

---

libraries/objectDefaultFiles/object.js
libraries/utilities.js
libraries/webInterface/gui/index.js
models/ObjectModel.js
server.js

This is a bug-fix for issue #110 
1. Handles network interface changes while the server is running.
2. Uses the next available interface if the defined interface is missing.
3. Prevents a crash if UDP can not send signals
4. Cleaned up all IP related code into one module

Fix for critical Bug

---

libraries/utilities.js

returns default size (0.3) if not found
also cleans up implementation a bit because the for loops weren't actually looping

fixes parsing xml for object targets without sizes

---

libraries/gitInterface.js
libraries/hardwareInterfaces.js
libraries/utilities.js
libraries/webFrontend.js
libraries/webInterface/gui/index.html
server.js

realityobjects -> spatialToolbox

---

server.js

1bf2491 is the actual bugfix, the other commit didn't seem necessary but is more consistent.

 Fix use of paths with unzipper on Windows

---

libraries/webInterface/gui/index.css
libraries/webInterface/gui/index.js

Add overflow prevention and hover text to netInterface elements

---

server.js

getInterfaces occasionally throws an error when my laptop is closed/hibernating, crashing the server

Fix intermittent crash when computer sleeps

---

package-lock.json
package.json
server.js

This shouldn't be merged yet because there's no reason to jeopardize the upcoming launch with the potential instability of an untested library

Replace sharp with Jimp

---

index.js
server.js

This helps a lot to identify what to do next, if reading the readme failed.

procide guidance insteat of error message

---

libraries/mobile/hardwareInterfaces.js
server.js

Push realtime settings to server from gui 
fix redirection of public folder files

Realtime settings to server from gui + fix redirection of public folder

---

libraries/utilities.js
routers/logic.js
routers/object.js
server.js

Ensures values sent to the server are alphanumeric with - and _ included for objects, frames, nodes, links, and blocks, and ensures paths sent by the user to the server are limited to child directories.

Added input sanitization on server-side

---

libraries/objectDefaultFiles/object.js
libraries/utilities.js
libraries/webInterface/gui/index.js

Update to UUID. We need to double check that the toolbox is able to handle the 15 Letter UUID instead of 12.

UUID Update

---

libraries/hardwareInterfaces.js
package.json
scripts/mobile-cleanup.sh
server.js

Fixes an issue where the mobile cleanup script would reinstall eslint. Removes lodash because we don't use it for anything important

More fun with dependencies

---

libraries/objectDefaultFiles/envelope.js
libraries/objectDefaultFiles/envelopeContents.js

Doesn't have the world position changes yet, this is just getting the starting code into the main repository

Envelope api improvements - subscribeToPosition of content tools

---

libraries/objectDefaultFiles/envelope.js
libraries/objectDefaultFiles/envelopeContents.js

adds worldCoordinates to messages passed between envelope and contents

sends world position between tools and envelope

---

libraries/objectDefaultFiles/gl-worker.js

Brings in the latest and greatest from the standalone project

Update gl worker

---

libraries/hardwareInterfaces.js

Needed to add listeners to nodes in hardware interfaces

Methods to get obj, tools, and nodes name by id

---

libraries/objectDefaultFiles/object.js

Allows a tool to display a message on the notification banner in the user interface

adds errorNotification API to object.js

---

controllers/link.js
libraries/hardwareInterfaces.js
server.js

This makes sure that once a link is created for a complex data node, the data node data is traveling to the destination right after. Its only processing this specific link for the data node.

Complext link trigger

---

server.js

Added the ability to upload glb files from area targets to enable navigation features in the toolbox.

Glb upload

---

server.js

The remote operator can use this to render icons at the location of all other remote operators

adds sockets for subscribing and sending camera positions across clients

---

libraries/objectDefaultFiles/object.js

to subscribe to the tool modelViewMatrix but where it's projected surface anchor on the groundplane is located

adds object.js addAnchoredModelViewListener API 

---

controllers/object.js
libraries/utilities.js
models/ObjectModel.js
server.js

Avatar objects can be created by the userinterface. They are deleted by the server when 1) a client disconnects (detected by socket disconnect), or 2) all avatar objects are deleted when the server restarts

Create and delete avatar objects

---

libraries/HumanPoseObject.js
server.js

The joint frames that are automatically created on the object are defined by a poseJointSchema passed in the post request, not predefined on the server. Deletes human pose objects whenever avatar objects are deleted (e.g. when server restarts or the client that saw the pose disconnects). Sets up an interval to delete stale human pose objects, but doesn't actually delete them yet.

Updated HumanPoseObject creation and deletion mechanisms

---

server.js

Allows the clients to discover the server (and which services it has) more quickly, since they send a ping message when they first open.

Sends server UDP beat in response to client 'ping' messages

---

server.js

Previous update and batchedUpdate users would always end their stream of updates with a separate API call to persist their modification (e.g. tool repositioning) but pose tracking doesn't have a nice end that's expected to happen regularly enough for this to make sense. Instead this writes directly to objects based on each property update which allows the objects variable to always be consistent with the user interface clients' state

Apply update messages to objects immediately

---

libraries/HumanPoseObject.js
libraries/recorder.js
routers/history.js
routers/object.js
server.js

Fixes up the existing recorder functionality to add periodic checkpoints and compression. This achieves a compression ratio of 0.2 with just gzip, the disabled compressFloat functionality adds another 0.8

History and logging

---

libraries/objectDefaultFiles/object.js

Enables
```
spatialInterface.getEnvironmentVariables().then(vars => {
console.log(vars.screenTopOffset, vars.layoutUIForPortrait);
})
```
etc.
Goes with https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/341

New tool API to getEnvironmentVariables

---

server.js

Improved speed of sending heartbeat of new objects from server to listeners. The objects appear quickly on client screens

Improved speed of sending heartbeat

---

libraries/objectDefaultFiles/object.js

Enables restoring region cards from spatialAnalytics tools

Add analyticsHydrateRegionCards api

---

routers/history.js

This should fix the issues with live data that @dangond-ptc and @ptc-mklaudiny reported

History compression fix

---

libraries/objectDefaultFiles/object.js

(enables spatial video recording on iPad)

update isDesktop function to distinguish between iPad and desktop 

---

libraries/HumanPoseFuser.js

Node versions less than 16 don't support this function

Replace use of Array.prototype.at(-1) with equivalent indexing

---

libraries/objectDefaultFiles/envelope.js

Writes Date.now() to the existing storage node every time the envelope opens

Persist envelope last open time

---

libraries/HumanPoseFuser.js
package-lock.json
package.json
server.js

I introduced new methods of fusing human objects from multiple views. More testing and tuning is needed to select the most reliable one in near term (eg. LiveWorx). It's easy to switch between them through flags without changing the current behaviour. I would like to have this merged since lot of the functionality will be useful down the line. 
Also, added new dependency  ml-matrix for linear algebra.

Human tracking multiview triangulation

---

libraries/objectDefaultFiles/object.js

The chat tool can use this to access the user's name and assign that name as the author of the messages you type.

adds getUserDetails tool API

---

.gitignore
libraries/HumanPoseFuser.js

Kept principal point definition as in Vuforia CL and fixed 3d to 2d projection in multiview triangulation.

Fixed use of Vuforia intrinsics

---

libraries/objectDefaultFiles/object.js

UI: https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/441
Server: https://github.com/ptcrealitylab/vuforia-spatial-edge-server/pull/846
Remote Operator Addon: https://github.com/ptcrealitylab/vuforia-spatial-remote-operator-addon/pull/108

patchHydrate and patchSetShaderMode Tool APIs

---

routers/history.js

Enables a pretty significant optimization to retrieving log files through the proxy

Allow direct access to compressed log files

---

libraries/objectDefaultFiles/object.js

Adds APIs that interact with the new profiling UI.
Goes with https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/521

Profiling apis

---

libraries/objectDefaultFiles/object.js

Adds new follow messages to object.js

Follow messages

---

.eslintignore
controllers/block.js
controllers/blockLink.js
controllers/link.js
controllers/logicNode.js
controllers/object.js
libraries/gitInterface.js
libraries/hardwareInterfaces.js
libraries/nodeUtilities.js
libraries/objectDefaultFiles/envelope.js
libraries/objectDefaultFiles/gl-worker.js
libraries/objectDefaultFiles/object.js
libraries/sceneGraph/SceneGraph.js
libraries/sceneGraph/SceneNode.js
libraries/sceneGraph/WorldGraph.js
libraries/serverHelpers/oauthRequestHandlers.js
libraries/webFrontend.js
libraries/webInterface/gui/index.js
server.js
tests/create-frame.test.js

All changes are expected to not change the behavior of the code, only make it look nicer

Fix all eslint warnings

---

constants.js
controllers/frame.js
controllers/logicNode.js
controllers/object.js
isMobile.js
libraries/HumanPoseFuser.js
libraries/addons/AddonFolderLoader.js
libraries/addons/AddonFrames.js
libraries/addons/AddonFramesSource.js
libraries/addons/Addons.js
libraries/addons/utilities.js
libraries/hardwareInterfaces.js
libraries/utilities.js
libraries/webFrontend.js
server.js
tests/addon-loading.test.js

Refactors out constants to new constants.js file. Throws in a small refactor to share more code in Addons and a test thereof.
yes I am very proud of this pun

Constant refactoring

---

libraries/utilities.js
server.js
tests/helpers.js
tests/object.test.js
tests/upload-target.test.js

There was a little scooch down into madness getting the test to work as an action but it's good* now.
*passed exactly once

 Add test for target uploading 

---

libraries/utilities.js
libraries/webFrontend.js
server.js

Picking these up in their own branch since they were mixed in with unrelated changes

Minor refactors

---

server.js

Requires https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/528

Set local ip on ios

---

libraries/objectDefaultFiles/styles/common.css

- notification styles added to common.css

notification style added

---

libraries/HumanPoseFuser.js

I made updates in HumanPoseFuser to support new human skeleton with full set of hand joints.
Related to UI repo PR - https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/546

Human tracking - full hands tracking

---

config.js
persistence/fsProm.js

Less stable than expected outside of testing environments

Pref off fs sync code

---

controllers/object.js
controllers/object/SplatTask.js
models/ObjectModel.js
routers/object.js
server.js
tests/upload-target.test.js

Need to change SPLAT_HOST for local configuration

Wire up requestGaussianSplatting API with persistent task backing

---

controllers/object/SplatTask.js

This commit fell through the cracks. Note that this is also the pathway to downloading the partial checkpoint target.splat and later downloading the final (complete) file

Download when step is complete

---

libraries/recorder.js
tests/recorder.test.js

tl;dr (more in commit message): diffing is 16x faster

Recorder is fast now

---

controllers/object.js
routers/object.js

Fix [#1027](https://github.com/ptcrealitylab/vuforia-spatial-edge-server/issues/1027)

Add alternative .zip-suffixed zipBackup route

---

server.js

Allows the server, if run with the --expose-gc flag, to clear out memory on an interval.

Add forced gc interval

---

controllers/object.js
controllers/object/SplatTask.js
routers/object.js

@hobinjk-ptc this may be a bit of a haphazard update to your SplatTask module, feel free to propose a cleaner implementation. Passes JWT from userinterface to the splat training server and passes error messages back to userinterface if not properly authenticated.

adds authentication and error handling to SplatTasks

---

libraries/objectDefaultFiles/object.js

Requires https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/732

Add raycasting against tools to object.js

---

libraries/webFrontend.js
server.js

Also small changes to ensure worlds have valid worldId and limit unnecessary error messages during initialization of objects with no .dat file

fix localhost:8080 tool list for empty worlds; 

---

controllers/object.js
routers/object.js

Send correct status code and error message in `/uploadMediaFile`

properly send formidable error to frontend in uploadMediaFile

---

libraries/objectDefaultFiles/object.js

@benptc This is what was missing from other branches

Add analyticsSetSensor API
