ptcrealitylab/vuforia-spatial-edge-server

libraries/hardwareInterfaces.js, server.js
new API for hardware Interfaces
server.setTool("object", "frame", "toolfolderName", __dirname);
server.clearTool("object", "frame");
Use this API if you want to deliver a default local tool with your interface.
Save your default tool in interfaces/interfaceName/tools/toolName/
=> Set tool to interface tools path

libraries/webFrontend.js, libraries/webInterface/gui/index.html, libraries/webInterface/gui/index.js, server.js
Instead of making them deactivated until you add a DAT/JPG target. Slight updates to UI to make it clearer that world objects are enabled by default but you can add an origin target to them:
=> Auto-initialize world objects without targets when created on frontend

libraries/webInterface/gui/index.css, libraries/webInterface/gui/index.html, libraries/webInterface/gui/index.js
Half of the references to Frames had already been switched to "tools". This just finishes the job, mostly by changing the "Add Frame" button to "Add Tool". Also updates tutorial text with new names, and clicking on the header brings you home.
Unfortunately, will need to update some existing tutorials that mention the "Add Frame" button, but I figure it's better to update this sooner rather than later.
=> Update web dashboard frames->tools

libraries/hardwareInterfaces.js, libraries/webInterface/gui/config.js, server.js
.. pushSettingsToGui API to hardware interfaces
Allows the "Manage Hardware Interface" config.html page to subscribe to live updates of the settings, if the hardware interface updates any of the settings after it loads.
How to use:
In your hardware interface, if you update the exports.settings, call:
```
server.pushSettingsToGui('name of your hardware interface', exports.settings);
```
In your config.html, include config.js:
```
<script src="../libraries/gui/config.js"></script>
```
Then create an InterfaceConfig, and subscribe to settings:
```
let interfaceConfig = new InterfaceConfig(realityServer.hardwareInterfaceName);
interfaceConfig.addSettingsUpdateListener(function(thisMsg) {
let settingName = 'randomNumber';
let settingValue = thisMsg.currentSettings[settingName].value; …
```
=> adds /subscribe/interfaceSettings socket to config.html pages and..

.github/workflows/nodejs.yml, package.json, server.js
Tests are currently failing because express-handlebars snuck in a change incompatible with node 6 but that doesn't impact us since we don't use express-handlebars on mobile
=> Further specify that node 6 is only supported for mobile devices

libraries/hardwareInterfaces.js
Currently requires a server or hardware interface restart between adding a target to a greyed-out object and the object having content and nodes
=> Add empty object folders for interfaces' addNode calls

libraries/webInterface/css/notifications.css, libraries/webInterface/gui/index.html, libraries/webInterface/gui/index.js, libraries/webInterface/gui/notifications.js, server.js
Adds a notification class that can be easily triggered to add an error or message to the top of the screen for a set amount of time or until the X is pressed. testing it out by adding one error notification if you upload a zip file without any target data to the drop zone. Will add more error notifications for other (currently silent) issues in the future.
=> Frontend notifications

libraries/webInterface/gui/index.js
A better wording and neutral color for when the dat file is not needed. #139
=> better user feedback for when instant image is used

libraries/utilities.js, server.js
Fixed an issue where attaching a target to an anchor would make the server advertise both the anchor-version and target-version of the object until the server restarts. JPEG support was added to allow iOS to upload images from the camera roll.
=> Anchor heartbeat bugfix and jpeg support

libraries/hardwareInterfaces.js, libraries/utilities.js, server.js
Resolved #184 #195 
Anchors now store their data in `.identity/object.json` instead of `object.json`.
addNode can now add nodes to anchors (was a bug caused by above issue) and can now create anchors immediately if one doesn't exist (previously it simply created an empty folder and returned without the node).
=> Hardware node anchor bugfix

server.js
a place to put CSS/JS/images etc.. there was currently no place to put extra files to include into config.html
=> statically serve the public folder in each hardware interface (if it exists) 

libraries/webInterface/gui/index.js, server.js
so that including libs from its public folder resolve correctly
E.g.
kepware config.html was previously was hosted at: http://localhost:8080/hardwareInterface/kepware
now it is hosted at: http://localhost:8080/hardwareInterface/kepware/config.html
So linking to `<link rel="stylesheet" href="public/test.css"/>` works correctly
=> change path for config.html to actually be the html file in the correct path

controllers/frame.js, controllers/logicNode.js, controllers/node.js, libraries/HumanPoseObject.js, libraries/gitInterface.js, libraries/hardwareInterfaces.js, libraries/recorder.js, libraries/utilities.js, libraries/webFrontend.js, models/Frame.js, models/Node.js, models/ObjectModel.js, server.js
Ensures that Objects, Frames, and Nodes are cast from JSON data to their classes whenever they are loaded into the system. Calls the node's exports.setup function from its constructor. Adds a de-constructor to each class that should be called when deleting it, which ensures that the instance is correctly removed from the system (currently the only effect is triggering the node's onRemove function, but could be expanded in the future)
=> Trigger node's exports.setup and exports.onRemove

models/Node.js
public data was being copied by reference (not by value) into each new node so they all shared the same publicData object on the server. so updating the public data of one node was updating them all.
E.g. when you added a drawing tool it would start out with the same drawing as the previously added drawing tools.
=> hotfix for nodes with public data

server.js
Fixes a small bug where an object's `objectId` property could mismatch the key used to index it in the `objects` data structure after uploading a target image to it.
=> correctly sets objectId property when uploading a new target image to an object

server.js
Allows the userinterface folder to be named either "userinterface" (for backwards compatibility) or "vuforia-spatial-toolbox-userinterface" (the default name when the repository is cloned)
Addresses issue https://github.com/ptcrealitylab/vuforia-spatial-toolbox-ios/issues/4
=> Update userinterface path

controllers/frame.js, controllers/object.js, libraries/hardwareInterfaces.js, libraries/utilities.js, libraries/webInterface/gui/index.css, libraries/webInterface/gui/index.html, libraries/webInterface/gui/index.js, server.js
- Updates web interface with tooltip help UI
- Fixes tool repositioning API so that scene graph doesn't use incorrect position data from tools inside of screens
- Adds a few hardwareInterface APIs that the screens interface can use to initialize new objects correctly, set their target size, and switch their visualization mode from AR to screen.
- Adds some error handling for target.xml files with invalid contents.
=> Updates for screens addon

controllers/node.js, models/Node.js
Corresponding server update for userinterface PR: https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/159
Fixes issue where invisibility and other node properties weren't sent back to the userinterface when a new node is initialized with the POST /addNode API
=> Sends newly initialized node data back to client

controllers/object.js, libraries/hardwareInterfaces.js, libraries/sceneGraph/SceneGraph.js, libraries/sceneGraph/SceneNode.js, libraries/sceneGraph/WorldGraph.js, libraries/utilities.js, libraries/webInterface/gui/index.html, libraries/webInterface/gui/index.js, models/ObjectModel.js, server.js
- adds .type to objects that supports object|world|human
- adds new /batchedUpdate socket message listener for more efficient realtime x,y,scale,etc updates
- clicking on world object name in localhost:8080 will open the remote operator if that add-on is set up
- removes some now-unnecessary logs
- fixes a couple tiny bugs
=> Object.type, human objects, batched realtime updates, etc

libraries/webInterface/gui/index.js, server.js
- fixes corrupted heartbeat checksums when server restarts
- catches error if there's an old server running on the network that doesn't support scenegraph APIs
-  adds a param when clicking on remote operator link (does nothing for now, but userinterface can make use of it later)
=> small stability improvements

libraries/objectDefaultFiles/object.js
to render the node on the screen instead of in 3D space
How to use in a tool:
```
realityInterface.initNode('left', 'node', -100, 0);
realityInterface.initNode('right', 'node', 100, 0);
realityInterface.initNode('top', 'node', 0, -100);
realityInterface.initNode('bottom', 'node', 0, 100);
realityInterface.stickNodeToScreen('left');
realityInterface.stickNodeToScreen('right');
realityInterface.stickNodeToScreen('top');
realityInterface.stickNodeToScreen('bottom');
```
=> adds API for stickNodeToScreen(nodeName) 

server.js
Zips from certain systems (including iOS NSFileManager) create an intermediate directory when zipping the directory. If file is named FILENAME.zip and contains a folder called FILENAME when unzipped, will search that directory for xml, dat, glb files in addition to top level.
Code follows style of containing function.
=> if target zip contains a folder of the same name, extracts files correctly from that folder

controllers/frame.js, libraries/hardwareInterfaces.js, routers/object.js
How does this look?
The request just needs frameType and relativeMatrix in the body and does all the other work to create the frame on the specified object and notify any clients to load it.
example: 
```
curl --header "Content-type: application/json" -d "{\"frameType\":\"graphUI\", \"relativeMatrix\":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}" http://localhost:8080/object/test_Peoqk0h4lgb/generateFrame 
```
^ This will create a graphUI frame and add it to my object named test (uuid = test_Peoqk0h4lgb), and position it centered on the object
=> adds a POST /object/:id/generateFrame route 

server.js
Forgot to add this before.. no need to restart server to clear subscriptions to disconnected clients
=> properly disconnects from sockets set up for client realtime interactions

libraries/objectDefaultFiles/object.js, server.js
Not sure if it was a browser update but need to ignore touches on html document as well as body element in order for them to pass thru open LOTO envelope and into the LOTO steps. Also adds a missing API `disableCustomInteractionMode` that LOTO can use to cancel out some special listeners it's using when the envelope is closed.
Also fixes one random typo with socket names that didn't seem to be causing any issues.
=> fix touch interaction APIs for loto envelope

controllers/object.js, libraries/utilities.js, server.js
New iOS app version will generate this file from the area target scanner and include it in the zip that is uploaded to the server. `target.unitypackage` is available at path, e.g. http://localhost:8080/obj/_WORLD_instantScan/target/target.unitypackage
=> adds support for optional unitypackage target file (in addition to xml, dat, and glb)

libraries/LocalUIApp.js, server.js
The decision to only LocalUIApp looks like it's out of sync with LocalUIApp also serving add-on resources.
After this it'll be possible to access /addons/vuforia-spatial-remote-operator-addon/content_resources/hololens.fbx at http://localhost:49368/addons/vuforia-spatial-remote-operator-addon/hololens.fbx
=> Always setup LocalUIApp; Serve fbx, gltf, and glb files

libraries/objectDefaultFiles/object.js
Tools can access the projectedZ from pointerevent listeners and also in the touchDecider function
e.g.
```
document.addEventListener('pointerdown', e => {
console.log(e.projectedZ);
})
```
or
```
spatialInterface.registerTouchDecider(e => {
console.log(e.projectedZ);
// ...
return intersects.length > 0;
})
```
=> adds a projectedZ property to touch events, if the userinterface provides it

server.js
Fixes bug where the device's local server wouldn't delete its own avatar (when Exit Button is pressed in pop-up app)
=> doesnt rely on a specific socket subscription when /disconnectEditor is received

server.js
trying to fix bug where occasionally instantScan worlds end up with .type='object' instead of 'world'. Fixed a more general mistake (perhaps causing side effects) where objects get re-created every time any target data is uploaded, rather than just the first time.
=> fix undefined thisObjectId, and standardize type='world' when isWorldObject=true

scripts/mobile-cleanup.sh, server.js
Running scripts/mobile-cleanup.sh will result in a pretty significant improvement to compile and install times. Other wins can be had by running `npm ci --omit=dev` in all the addon folders and removing `@ffmpeg-installer/ffmpeg` from the remote operator addon.
=> Mobile cleanup update

libraries/StaleObjectCleaner.js, libraries/sceneGraph/SceneGraph.js, server.js
On a rolling basis, deletes avatar and human objects unless a realtime batchedUpdate or a sceneGraph update references the object within the last (30 or 60) seconds, or unless a keepObjectAlive heartbeat message has been received in the same timeframe.
=> Uses StaleObjectCleaner and heartbeats to delete old avatars and human pose objects

libraries/objectDefaultFiles/object.js
Usage:
spatialInterface.subscribeToObjectsOfType('human', (result) => {
/*
{
objectId: {
matrix: [...], // worldMatrix
worldId: '_WORLD_xyz',
tools: {
toolId: [...], // localMatrix
...
}
},
...
}
*/
});
=> adds new API, spatialInterface.subscribeToObjectsOfType(type, callback)

libraries/HumanPoseObject.js, server.js
add deconstruct method to human pose objects on server so they can be properly deleted, and shorten life of unobserved pose objects to 15sec.
Also renames the pose joint frames to use the values of the enum, e.g. "nose" rather than the keys of the enum, e.g. "NOSE"
=> Small adjustments for human objects

libraries/objectDefaultFiles/object.js
@dangond-ptc you can use this in the spatialDraw tool now. Fullscreen/stickyfullscreen takes precedent over this so you can leave it on and it won't affect the threejs scene within the tool, only when it's in the icon view.
=> adds spatialInterface.setAlwaysFaceCamera(true) API to toggle billboarding effect for 2D tools

config.js, controllers/block.js, controllers/blockLink.js, controllers/frame.js, controllers/link.js, controllers/logicNode.js, controllers/node.js, controllers/object.js, libraries/gitInterface.js, libraries/hardwareInterfaces.js, libraries/nodeUtilities.js, libraries/utilities.js, libraries/webFrontend.js, server.js
In a perfect world, every injection of objectsPath (and other shared variables) is done by requiring a file so we don't have error-prone calls to setup(every, variable, in, server, dot, js) but it's not really a high priority to fix this considering the server currently works
=> Start of objectsPath refactor

libraries/HumanPoseObject.js
JS receives now human joints in WCS and mm units at the start. All conversions are moved to Swift.
Related to PR in ToolboxApp (https://github.com/ptcrealitylab/vuforia-spatial-toolbox-ios-swift/pull/258).
=> Removed conversion from m to mm (handled in Swift app code)

libraries/recorder.js, routers/history.js, server.js
Running in the exit handler requires a synchronous persist function. PR also changes the behavior of the asynchronous version to never skip updates. Both this new approach and the old approach will lose data in the event of a compression/write error
=> Persist recorder log on exit instead of on sigint

controllers/object.js, routers/object.js, server.js
Deprecates the old way to delete objects, which was with:
POST /
{
action: 'delete',
name: `${object.name}`,
frame: ''
}
You can now delete an object with:
DELETE `/object/${objectID}`
This is consistent with how to delete frames (tools), which is currently done with:
DELETE `/object/${objectID}/frames/${frameID}`
=> adds new DELETE /object/${objectID} route for manager to use

server.js
Avatar heartbeats come every 1 second with https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/367, so deleting an avatar if no heartbeats within the past 5 seconds seems reasonable to me.
=> delete avatar object if we haven't heard its heartbeat in the last 5 seconds

libraries/utilities.js
A proposed solution to the crash log that happened to me:
```
2023-03-07T20:22:25.551Z - debug: received /disconnectEditor with editorId: zY1mptc8 
2023-03-07T20:22:25.552Z - debug: delete avatar objects associated with zY1mptc8 
2023-03-07T20:22:25.552Z - debug: Deleting object: _AVATAR_zY1mptc8_desktop 
2023-03-07T20:22:25.558Z - debug: i deleted: _AVATAR_zY1mptc8_desktop_f45h0at3qgi 
Downloading started
2023-03-07T20:22:25.572Z - debug: delete human pose objects associated with zY1mptc8 
/private/var/containers/Bundle/Application/BA52829A-94DF-476D-BAA6-FFDFEF551ED7/Vuforia Spatial Toolbox.app/vuforia-spatial-edge-server/libraries/utilities.js:386
var outputFilename = objectsPathBuffered + '/' + objects[obj].name + '/' + identityFolderName + '/object.json';
^
TypeError: Cannot read …
```
=> prevent app crash if object deleted while write pending

libraries/objectDefaultFiles/envelope.js, libraries/objectDefaultFiles/object.js
Action item: for our three.js tools, add code along these lines to make everything render correctly in response to the API:
```
spatialInterface.onWindowResized(({width, height}) => {
console.log('onWindowResized');
mainData.width = width;
mainData.height = height;
rendererWidth = width;
rendererHeight = height;
aspectRatio = rendererWidth / rendererHeight;
renderer.setSize(rendererWidth, rendererHeight);
realRenderer.setSize(rendererWidth, rendererHeight);
isProjectionMatrixSet = false;
spatialInterface.subscribeToMatrix(); // this should trigger a new retrieval of the projectionMatrix
});
```
Requires: https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/388
=> adds onWindowResized tool API

config.js, libraries/utilities.js, server.js
If the UDP client.send fails for a heartbeat or action message, tries to send the message to connected clients over an existing websocket.
=> Make server work on non-UDP-compatible networks

libraries/HumanPoseFuser.js, libraries/HumanPoseObject.js
I noticed issues with auxiliary poses during playback from recorder json. I realised that null value is not supported by recorder. So I changed parent property value from null to 'none' for 'no parent' semantics ().
=> Issue with null value of parent property of human object

libraries/objectDefaultFiles/envelope.js
The "close" button fully closes the tool. The "minimize" button makes the tool lose "focus" (I use the terminology "blur" to mean the opposite of focus). Tools can use envelope.onBlur(() => { ... }) to update their UI when the tool isn't interactable.
=> add onFocus and onBlur events to the envelope.js library

libraries/objectDefaultFiles/envelope.js
This seems to be the least invasive way to make the envelopes with a 3D scene sync across clients, while making the fully-2D envelopes (chat, search, etc) personal to each user.
Goes with https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/421
=> only utilizes the open node of an envelope if the tool isnt running in full2d mode

libraries/objectDefaultFiles/envelope.js
When another client reads the 'open' node of the envelope, blurs the envelope after opening it. This covers all cases where the envelope is synchronizing with a remote client's state. Locally, different methods are used to trigger the opening, and these don't include the blur message.
Logic is getting a bit messy, as the envelope needs to ignore doing the blur when it's reading its defaultValue after first creating the node. But seems to work consistently in my tests.
PR for userinterface: https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/pull/422
=> Open envelopes minimized for other clients

libraries/HumanPoseFuser.js, server.js
Added new property 'updatedByChildren' to only fused human objects. This represents a current best human object updating the fused object. It is designed as array because it can be tru fusion of multiple objects (views) in next iteration.
Possible states of the property are: 
undefined  - for standard human objects generated by toolbox apps
['none'] - for fused human objects; no object currently updating fused object  (unlikely but possible scenario)
['\_HUMAN\_**deviceVJ4ubfsh**_pose1__O26kv6p852m']  - for fused human objects; objectId of standard human object which is currently selected.
The bold substring (from editor uuid) should be used to derive which camera/app is currently driving the fused human object. For the standard objects which don't have the property defined , this can be …
=> Human tracking updated by children property

libraries/objectDefaultFiles/envelope.js
This prevents the following case:
Alice opens spatialDraw with 2d ui
spatialDraw opens on Beth's RO minimized
Beth fully opens spatialDraw
spatialDraw minimizes on Alice's RO despite Alice wanting it fully open
=> Only open envelope minimized if the envelope is not already open

libraries/HumanPoseFuser.js
Best single-view poses are translated to be close to a pose linearly interpolated from pose from multiple views.
This is a backup method behind a flag to have more alternatives if we see too big jumps when the best camera is switched at Liveworx.
=> Added new mode for human object fusion 

server.js
This should make the client realize its object got deleted and it should refresh its local state.
=> Trigger reloadObject if a remote client sends a property update of an unknown object

libraries/utilities.js
One of many possible race conditions that may cause the issue where settings on iOS mysteriously reset
=> If an error occurs during reading hardwareInterface settings, only reset to {} as a default

libraries/objectDefaultFiles/styles/common.css, server.js
This is a very quick first proposal for where to put shared styles that multiple tools can make use of. Open to suggestions.
Adds a common.css file that for now just contains the tool-color-gradient style for the minimized icon shimmer
Tools can use these files like so: `<link rel="stylesheet" href="objectDefaultFiles/styles/common.css">`
(example: https://github.com/ptcrealitylab/pop-up-onboarding-addon/pull/84)
=> adds objectDefaultFiles/styles directory to contain any shared css files

libraries/objectDefaultFiles/object.js
Adds a new API that is used as a central place to subscribe to a list of matrices related to various coordinate systems / matrices that the tool may be interested in.
Can be used like so (example taken from an updated version of the onshape tool that I made):
```
spatialInterface.subscribeToCoordinateSystems([
spatialObject.COORDINATE_SYSTEMS.CAMERA,
spatialObject.COORDINATE_SYSTEMS.PROJECTION_MATRIX,
spatialObject.COORDINATE_SYSTEMS.TOOL_GROUND_PLANE_SHADOW,
], (coordinateSystems) => {
// callback function
let cameraMatrix = coordinateSystems[spatialObject.COORDINATE_SYSTEMS.CAMERA];
let projectionMatrix = coordinateSystems[spatialObject.COORDINATE_SYSTEMS.PROJECTION_MATRIX];
let toolGroundPlaneShadowMatrix = coordinateSystems[spatialObject.COORDINATE_SYSTEMS.TOOL_GROUND_PLANE_SHADOW]; …
```
=> New matrix APIs, separating camera and scene coordinate systems

libraries/utilities.js, server.js
Under some conditions the jpg contained in the target zip has already been moved/processed before the call to `rename`
=> Fix crash due to race condition during target zip upload

routers/history.js
Server crashed when loading analytics data from history due to fsProm.exists not...existing. Replaced it with fsProm.stat, which is the recommended way of checking if a file exists. Also ensured createReadStream continues to use old-fashioned `fs`, since fsProm.createReadStream also does not exist.
=> Fs prom exists fix

controllers/object.js, libraries/sceneGraph/SceneNode.js
Fixes an issue where setParent would introduce a cycle into the scene graph due to treating secondary world objects like children of the first observed world object. Honestly not sure what the correct behavior would be, but I'm at least confident that it's not get stuck recursing forever.
=> Prevent cycles from setParent; Fix overwriting worldId of world object

controllers/frame.js, controllers/logicNode.js, controllers/object.js, libraries/nodeUtilities.js, libraries/utilities.js, libraries/webFrontend.js, server.js
Various calls can throw exceptions if e.g. trying to delete a file which
already doesn't exist, so this wraps all patterns where condition is
checked -> condition is acted on with exception handlers for the case
where the condition changes during function execution. Introduces
mkdirIfNotExists and unlinkIfExists for this purpose
Tries to identify places where changes in a global variable (`objects`,
it's always `objects`) could happen during the execution of an async
function and break preconditions (usually the deletion of objects[key]).
Also wraps some potentially problematic calls to fs apis that could
throw.
=> Safer logic around fs access and async/await

logger.js
Not sure if there's a better approach for this, but currently I'm getting hundreds of warning lines from the decompress-zip library every time I use it to decompress the target.dat (which I do on server restart to ensure the file didn't change while the server was off), like:
```
2024-01-12T20:03:10.652Z - warn: Possibly unsupported ZIP platform type, 19 
2024-01-12T20:03:10.652Z - warn: Possibly unsupported ZIP platform type, 19 
2024-01-12T20:03:10.652Z - warn: Possibly unsupported ZIP platform type, 19 
...
2024-01-12T20:03:10.652Z - warn: Possibly unsupported ZIP platform type, 19
```
This seems to work for suppressing those messages.
=> configure winston to ignore spammy decompress-zip warnings

libraries/objectDefaultFiles/object.js
New tools now initialize properly on slow networks, previous method sent subscribe method before socket was ready, resulting in no subscription being created.
This fixes the following bugs:
• On slow networks, placing a tool fails to load the tool, despite creating it on the server
• On slow networks, new tools added by other users fail to subscribe to publicData messages, and can only write, not read updates
To reproduce said network conditions, set network speed to Slow 3G in Chrome's network pane, Fast 3G reproduces these bugs only sometimes.
=> New tools now initialize properly on slow networks

libraries/recorder.js
Reduces the recorder's impact on the filesystem by only creating a new
log file if that log file contains differences from the last (or if it's the first call to persist after starting the server).
Also minor fix for potential bug (that doesn't happen in practice)
Close #1004
=> Recorder: Only save files with differences

libraries/BatchedUpdateAggregator.js, server.js
Clients can optionally provide their previous round-trip time when they make their next /status check, and the BatchedUpdateAggregator uses these values to help monitor congestion and throttle the rate at which it batches and broadcasts /batchedUpdate messages.
The final batching interval is a combination of the number of active clients and average recent round-trip times. Compared to the previous version, it keeps the interval faster for longer (as more and more clients connect and move around) until the ping time of clients begins to degrade, rather than dropping FPS while the network is still healthy.
=> Optimize update aggregator

.gitignore, package-lock.json, package.json, tests/server-remote-operator.test.js
After `npm run test` coverage-ui will now include a report on the coverage of the ui code from server-remote-operator.test.js
=>  Add report of puppeteer coverage 
